services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=PatientManagementDB'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'



